global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'broker'

scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          __metrics_path__: /manager/prometheus/metrics

  - job_name: 'rabbit'
    scrape_interval: 10s
    static_configs:
      - targets: ['rabbit:15692']

